/**
 * QuerySafety Guardrail
 * A non-AI utility to intercept and validate SQL queries generated by agents.
 * Ensures that only read-only (SELECT) queries are executed.
 */

const BLOCKED_KEYWORDS = [
    'DROP',
    'DELETE',
    'UPDATE',
    'INSERT',
    'ALTER',
    'TRUNCATE',
    'CREATE',
    'REPLACE',
    'GRANT',
    'REVOKE',
    'EXEC',
    'SHUTDOWN',
    'RENAME'
]

export function validateQuery(sql: string): { safe: boolean; error?: string } {
    const upperSql = sql.toUpperCase().trim()

    // 1. Must start with SELECT (or WITH for CTEs)
    if (!upperSql.startsWith('SELECT') && !upperSql.startsWith('WITH')) {
        return {
            safe: false,
            error: 'Only SELECT (read-only) queries are permitted.'
        }
    }

    // 2. Check for blocked keywords
    // We use word boundaries to avoid false positives (e.g., a column named "update_at")
    for (const keyword of BLOCKED_KEYWORDS) {
        const regex = new RegExp(`\\b${keyword}\\b`, 'i')
        if (regex.test(sql)) {
            return {
                safe: false,
                error: `Unsafe operation detected: '${keyword}' is not allowed.`
            }
        }
    }

    // 3. No semicolon-separated multiple queries
    if (sql.includes(';')) {
        const statements = sql.split(';').filter(s => s.trim().length > 0)
        if (statements.length > 1) {
            return {
                safe: false,
                error: 'Multiple statements are not allowed.'
            }
        }
    }

    return { safe: true }
}
