'use client'

import { useQuery } from '@tanstack/react-query'
import { apiRequest } from '@/lib/api'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Brain, Calendar, FileText, ChevronRight, List } from 'lucide-react'
import Link from 'next/link'
import { formatDate } from '@/lib/utils'
import { Skeleton } from '@/components/ui/skeleton'
import { Navigation } from '@/components/layout/navigation'
import { AuthGuard } from '@/components/auth-guard'

async function fetchAIReports() {
    const response = await apiRequest('/api/ai-analysis')
    if (!response.ok) throw new Error('Failed to fetch reports')
    return response.json()
}

export default function AIAnalysisListPage() {
    const { data, isLoading } = useQuery({
        queryKey: ['ai-reports'],
        queryFn: fetchAIReports,
    })

    return (
        <AuthGuard>
            <div className="min-h-screen bg-background">
                <Navigation />
                <main className="container mx-auto py-6">
                    <nav className="flex items-center space-x-2 text-sm text-muted-foreground mb-6">
                        <Link href="/" className="hover:text-foreground transition-colors flex items-center">
                            <List className="h-4 w-4 mr-1" />
                            ER List
                        </Link>
                        <ChevronRight className="h-4 w-4" />
                        <span className="text-foreground font-medium flex items-center">
                            <Brain className="h-4 w-4 mr-1" />
                            AI Reports
                        </span>
                    </nav>

                    <div className="space-y-6">
                        <div className="flex items-center justify-between">
                            <div>
                                <h1 className="text-3xl font-bold tracking-tight">AI Reports</h1>
                                <p className="text-muted-foreground">
                                    Custom analysis generated by the strategic engine.
                                </p>
                            </div>
                            <Brain className="h-8 w-8 text-primary opacity-20" />
                        </div>

                        {isLoading ? (
                            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                                {[1, 2, 3].map((i) => (
                                    <Skeleton key={i} className="h-48 w-full rounded-xl" />
                                ))}
                            </div>
                        ) : data?.items?.length > 0 ? (
                            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                                {data.items.map((report: any) => (
                                    <Link key={report.id} href={`/ai-analysis/${report.id}`}>
                                        <Card className="h-full transition-all hover:border-primary/50 hover:shadow-md cursor-pointer group">
                                            <CardHeader className="pb-3">
                                                <div className="flex items-start justify-between">
                                                    <div className="p-2 rounded-lg bg-primary/10 text-primary mb-2">
                                                        <FileText className="h-5 w-5" />
                                                    </div>
                                                    <ChevronRight className="h-5 w-5 text-muted-foreground transition-transform group-hover:translate-x-1" />
                                                </div>
                                                <CardTitle className="line-clamp-2 text-lg">
                                                    {report.title}
                                                </CardTitle>
                                            </CardHeader>
                                            <CardContent>
                                                <div className="flex flex-col gap-2 text-sm text-muted-foreground">
                                                    <div className="flex items-center gap-2">
                                                        <Calendar className="h-4 w-4" />
                                                        {formatDate(report.createdAt)}
                                                    </div>
                                                    <div className="flex items-center gap-2">
                                                        <Brain className="h-4 w-4" />
                                                        {report.erCount} ERs Analyzed
                                                    </div>
                                                </div>
                                            </CardContent>
                                        </Card>
                                    </Link>
                                ))}
                            </div>
                        ) : (
                            <Card className="flex flex-col items-center justify-center p-12 bg-muted/30 border-dashed">
                                <Brain className="h-12 w-12 text-muted-foreground mb-4 opacity-50" />
                                <p className="text-lg font-medium text-muted-foreground">No reports found</p>
                                <p className="text-sm text-muted-foreground text-center max-w-sm mt-2">
                                    Select ERs in the main table and click on 'IA Analysis' to generate your first strategic report.
                                </p>
                            </Card>
                        )}
                    </div>
                </main>
            </div>
        </AuthGuard>
    )
}
